dist: bionic

language: node_js

node_js:
  - "12"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make && make docker/run target=lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-config-aggregator
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-config-aggregator v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-config-aggregator/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: JXBSubJJt5+vjzJpIYXYMBEyZBBZOTbw+16BaVouEQj14NEd5fCLBHIlZTb6BgJYAIF33RqA9I6v+9EuSxYLcY6rGwjegdIyMHw8YJjb3iz79C9Lt00hLt5jQyR6sYzZe1AgmYiXm4jF7VPZGyx+vbWEnMov2N7VXrRMnbHTmUwYExmXBVyMFGG1OqcjZoYysfxGx5i4oOp4Xuo/mcxI8/zBvgI+3LO4+9TcqYms2YTPhvaC5WCOVvYCjxQ6WyZFn0EnCp4ALrl/vsbedyc7ze9DuQnPhnSPMxS1eVbu6rFOJXchjgTDfNwhSUeKi5Gliq3L1XrsJ8e3XgHwzvTWq58TCOoN5/ihsQPixPxM/+4He5GEaAU/DqGFSrIatL0OpZQAEsuli3lH/Nko5ArSItRIUHTkdaN1oDbdr1a5/mgNQ/Xu+nwx3f/ttSy9cQige27OzmK7/t8pKrSFW1AtbMIRwY1sL4/F0ZjiO0pZwjCcp5rnMX7KEI3+lHu+BMPgmcPANMvDFxLLwIlBs2yvB90F/JpCDo86sO+tmO+cR6Ix1nkPO5eFJX2tsTRwOBTCfUTvEQG+Nfb32WnVSpZNN96c/dJOloioyKNn7qyOrX/EobLFXMslc94BBjGR5NNPDxtNU5GXcJ1jjQzKRSm7Bh9SG6NcFH4YUYAiDo+6Hr4=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-config-aggregator
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
